[package]
name = "alba-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
rand_core = "0.6.4"
num-bigint = "0.4.0"
num-traits = "0.2"
more-asserts = "0.3.1"
hex = "0.4"

[dev-dependencies]
rand_chacha = "0.3.1"