//! Test & Bench helpers

use alba::utils::types::Element;
use blake2::digest::{Update, VariableOutput};
use blake2::Blake2bVar;
use rand_chacha::ChaCha20Rng;
use rand_core::RngCore;
use std::collections::HashSet;

/// Generate a set of indexed items given the set size and a seed
/// Items are generated by hashing the current iteration index
/// Index of the item is randomly generated
pub(crate) fn gen_items_with_index<const N: usize>(
    seed: &[u8],
    set_size: u64,
    rng: &mut ChaCha20Rng,
) -> Vec<Element<[u8; N]>> {
    let mut s_p: Vec<Element<[u8; N]>> = Vec::with_capacity(set_size as usize);
    let mut seen: HashSet<(Vec<u8>, u64)> = HashSet::with_capacity(set_size as usize);
    let mut data_buf: [u8; 8];

    for b in 0..set_size {
        data_buf = b.to_be_bytes();
        let mut digest_buf: [u8; N] = [0u8; N];
        let mut hasher = Blake2bVar::new(N).expect("Failed to construct hasher!");
        hasher.update(seed);
        hasher.update(&data_buf);
        hasher
            .finalize_variable(&mut digest_buf)
            .expect("Failed to finalize hashing");

        let index = loop {
            let candidate = rng.next_u64();
            if seen.insert((digest_buf.to_vec(), candidate)) {
                break candidate;
            }
        };
        s_p.push(Element::new(digest_buf, Some(index)));
    }
    s_p
}

/// Generate a set of items with no index given the set size and a seed
/// Items are generated by hashing the current iteration index
pub(crate) fn gen_items_no_index<const N: usize>(
    seed: &[u8],
    set_size: u64,
) -> Vec<Element<[u8; N]>> {
    let mut s_p: Vec<Element<[u8; N]>> = Vec::with_capacity(set_size as usize);
    let mut data_buf: [u8; 8];
    let mut digest_buf: [u8; N] = [0u8; N];
    for b in 0..set_size {
        data_buf = b.to_be_bytes();
        let mut hasher = Blake2bVar::new(N).expect("Failed to construct hasher!");
        hasher.update(seed);
        hasher.update(&data_buf);
        hasher
            .finalize_variable(&mut digest_buf)
            .expect("Failed to finalize hashing");
        s_p.push(Element::new(digest_buf, None));
    }
    s_p
}
