[book]
authors = ["Arnaud Bailly"]
language = "en"
multilingual = false
src = "src"
title = "ALBA"

[output.html]
mathjax-support = true
additional-css = ["alba.css"]
additional-js = ["alba.js", "chart.js"]
