name: Deploy Website

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4

      - name: 🪨 Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.40'

      - name: 📓 Build website
        run: mdbook build website

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/book
          cname: alba.cardano-scaling.org
